import { buildAnalysisResult } from "./pipeline";
import type { DetectedProduct, OffEnrichment } from "./types";

const DEMO_PRODUCTS: DetectedProduct[] = [
  {
    id: "product-1",
    product_name: "Croc’ Choco",
    brand: "P’tit Matin",
    price: 1.2,
    quantity: "600 g",
    quantity_amount: 600,
    quantity_unit: "g",
    price_per_unit: 2,
    price_unit: "kg",
    barcode: null,
    bounding_box: { x: 0.067, y: 0.2, width: 0.183, height: 0.44 },
    confidence: 0.98,
    identity_confidence: 0.98,
    price_confidence: 0.99,
    price_product_match_confidence: 0.98,
    promotion_text: null,
  },
  {
    id: "product-2",
    product_name: "Muesli Fruits",
    brand: "Monts & Graines",
    price: 2.8,
    quantity: "700 g",
    quantity_amount: 700,
    quantity_unit: "g",
    price_per_unit: 4,
    price_unit: "kg",
    barcode: null,
    bounding_box: { x: 0.283, y: 0.2, width: 0.183, height: 0.44 },
    confidence: 0.98,
    identity_confidence: 0.98,
    price_confidence: 0.99,
    price_product_match_confidence: 0.98,
    promotion_text: null,
  },
  {
    id: "product-3",
    product_name: "Avoine Pure",
    brand: "Grain Matin",
    price: 4.8,
    quantity: "400 g",
    quantity_amount: 400,
    quantity_unit: "g",
    price_per_unit: 12,
    price_unit: "kg",
    barcode: null,
    bounding_box: { x: 0.5, y: 0.2, width: 0.183, height: 0.44 },
    confidence: 0.98,
    identity_confidence: 0.98,
    price_confidence: 0.99,
    price_product_match_confidence: 0.98,
    promotion_text: null,
  },
  {
    id: "product-4",
    product_name: "Granola Noix",
    brand: "L’Atelier Croustillant",
    price: 3.75,
    quantity: "500 g",
    quantity_amount: 500,
    quantity_unit: "g",
    price_per_unit: 7.5,
    price_unit: "kg",
    barcode: null,
    bounding_box: { x: 0.717, y: 0.2, width: 0.183, height: 0.44 },
    confidence: 0.98,
    identity_confidence: 0.98,
    price_confidence: 0.99,
    price_product_match_confidence: 0.98,
    promotion_text: null,
  },
];

const DEMO_OFF: OffEnrichment[] = [
  {
    code: "0000000000001",
    product_name: "Croc’ Choco",
    brand: "P’tit Matin",
    quantity: "600 g",
    nutri_score: "d",
    sugars_100g: 28,
    additives_count: 3,
    additives: ["demo:e322", "demo:e476", "demo:e500"],
    nova_group: 4,
    ingredients_text: "Maïs, sucre, cacao, huile de tournesol.",
    match_confidence: 1,
    source_url: null,
  },
  {
    code: "0000000000002",
    product_name: "Muesli Fruits",
    brand: "Monts & Graines",
    quantity: "700 g",
    nutri_score: "b",
    sugars_100g: 12,
    additives_count: 0,
    additives: [],
    nova_group: 3,
    ingredients_text: "Flocons d’avoine, raisins, pomme, amandes.",
    match_confidence: 1,
    source_url: null,
  },
  {
    code: "0000000000003",
    product_name: "Avoine Pure",
    brand: "Grain Matin",
    quantity: "400 g",
    nutri_score: "a",
    sugars_100g: 1,
    additives_count: 0,
    additives: [],
    nova_group: 1,
    ingredients_text: "Flocons d’avoine complets.",
    match_confidence: 1,
    source_url: null,
  },
  {
    code: "0000000000004",
    product_name: "Granola Noix",
    brand: "L’Atelier Croustillant",
    quantity: "500 g",
    nutri_score: "c",
    sugars_100g: 17,
    additives_count: 1,
    additives: ["demo:e322"],
    nova_group: 3,
    ingredients_text: "Avoine, noix, miel, huile de colza.",
    match_confidence: 1,
    source_url: null,
  },
];

export function getDemoAnalysis() {
  return buildAnalysisResult(DEMO_PRODUCTS, DEMO_OFF, "demo", 850);
}
